Repository cloudposse/.github, pull requests merged in 2024-03, with the labels that each got.

#44 Add missing migration label
  .github/mergify.yml
  .github/settings.yml
Labels: triage, needs-cloudposse

#45 Update README.md.gotmpl
  README.md.gotmpl
Labels: triage

#47 display templates depending on available sections
  README.md
  README.md.gotmpl
Labels: triage

#48 Fix templates in README.md.gotmpl
  README.md
  README.md.gotmpl
Labels: triage

#49 Add more conditions for mergify config
  .github/mergify.yml
  migrate/Makefile
  migrate/README.md
Labels: triage, needs-cloudposse

#51 Added shared auto release workflow
  .github/workflows/shared-auto-release.yml
Labels: needs-cloudposse

#53 Update shared-auto-release config name
  .github/workflows/shared-auto-release.yml
Labels: needs-cloudposse

#54 Auto release fix
  .github/workflows/auto-release.yml
Labels: triage, needs-cloudposse

#56 Set `release` environment for `shared-auto-release` workflow
  .github/workflows/shared-auto-release.yml
Labels: needs-cloudposse

#58 Prevent looping on triage label
  .github/mergify.yml
Labels: bugfix, triage, needs-cloudposse

#60 Rename auto-release.yml to auto-release-2.yml
  .github/auto-release-2.yml
Labels: triage, needs-cloudposse

#61 Rename auto-release-2.yml to auto-release.yml
  .github/auto-release.yml
Labels: triage, needs-cloudposse

#62 `auto-release.yaml` enable filter-by-commitish
  .github/auto-release.yml
Labels: triage, needs-cloudposse

#63 Create auto-release-hotfix.yml
  .github/auto-release-hotfix.yml
Labels: triage, needs-cloudposse
