Repository cloudposse/.github, pull requests merged in 2024-09, with the labels that each got.

#118 feat: add scorecard
  workflow-templates/scorecard.yml
Labels: triage

#119 Add `terratest` environment
  .github/settings.yml
Labels: needs-cloudposse

#117 Terratest refactoring
  .github/workflows/shared-terraform-chatops.yml
Labels: needs-cloudposse

#122 Restrict role that can run terratest
  .github/workflows/shared-terraform-chatops.yml
Labels: needs-cloudposse

#123 Debug terratest commenter
  .github/workflows/shared-terraform-chatops.yml
Labels: triage, needs-cloudposse

#124 Added terratest user permissions
  .github/workflows/shared-access-controller.yml
  .github/workflows/shared-terraform-chatops.yml
Labels: needs-cloudposse

#116 Update settings for github actions
  migrate/migrations/20240716/README.md
  migrate/migrations/20240716/repos-00
  migrate/migrations/20240716/repos-01
  migrate/migrations/20240716/repos-02
  migrate/migrations/20240716/repos-03
  migrate/migrations/20240716/repos.sh
  migrate/migrations/20240716/repos.txt
  migrate/migrations/20240716/script.sh
Labels: triage, needs-cloudposse

#128 Added read custom properties for terratest
  .github/workflows/shared-terraform-chatops.yml
Labels: triage, needs-cloudposse
