Repository cloudposse/.github, pull requests merged in 2025-02, with the labels that each got.

#139 Add runner configuration for Runs-On
  .github/runs-on.yml
Labels: triage, needs-cloudposse

#140 Updated runs-on confguration
  .github/runs-on.yml
Labels: needs-cloudposse

#141 [RunsOn] Limit instance families to standard types
  .github/runs-on.yml
Labels: patch, needs-cloudposse

#143 Free space before run go releaser
  .github/workflows/shared-go-auto-release.yml
Labels: triage, needs-cloudposse

#144 Fix free space go releaser
  .github/workflows/shared-go-auto-release.yml
Labels: triage, needs-cloudposse

#146 Check free space size
  .github/workflows/shared-go-auto-release.yml
Labels: triage, needs-cloudposse

#147 Move GHA runners to public subnets
  .github/runs-on.yml
Labels: minor, needs-cloudposse

#148 Go releaser use default parallelism
  .github/workflows/shared-go-auto-release.yml
Labels: triage, needs-cloudposse

#150 Add auto-pre-release config
  .github/auto-pre-release.yml
Labels: triage, needs-cloudposse
