Repository cloudposse/.github, pull requests merged in 2025-05, with the labels that each got.

#166 Move shared workflows
  .github/workflows/shared-ci-github-action.yml
  .github/workflows/shared-github-action.yml
  .github/workflows/shared-readme.yml
Labels: triage, needs-cloudposse

#165 Create shared-codeowners
  .github/workflows/shared-codeowners.yml
Labels: triage, needs-cloudposse

#168 Create shared-сi-terraform.yml
  .github/workflows/shared-scheduled-context.yml
  .github/workflows/shared-terraform-module.yml
  .github/workflows/shared-terraform-scheduled.yml
  .github/workflows/shared-сi-terraform.yml
Labels: triage, needs-cloudposse

#170 Fix terraform module CI
  .github/workflows/shared-terraform-module.yml
Labels: triage, needs-cloudposse

#171 Update shared-terraform-module.yml
  .github/workflows/shared-ci-terraform.yml
Labels: triage, needs-cloudposse

#172 Create shared-ci-typescript-app-check-dist.yml
  .github/workflows/shared-ci-typescript-app-check-dist.yml
Labels: triage, needs-cloudposse

#173 chore: allow terratest user
  .github/workflows/shared-access-controller.yml
Labels: triage, needs-cloudposse

#174 Rebuild readme with atmos
  README.md.gotmpl
Labels: triage

#176 Readme template support GHA
  README.md.gotmpl
Labels: triage

#175 Use atmos to generate readme
  .github/atmos/terraform-module.yaml
  .github/workflows/shared-ci-terraform.yml
  .github/workflows/shared-readme.yml
  migrate/migrations/20250523/README.md
  migrate/migrations/20250523/repos-00
  migrate/migrations/20250523/repos-01
  migrate/migrations/20250523/repos-02
  migrate/migrations/20250523/repos-03
  migrate/migrations/20250523/repos-04
  migrate/migrations/20250523/repos-05
  migrate/migrations/20250523/repos-06
  migrate/migrations/20250523/repos-07
  migrate/migrations/20250523/repos-08
  migrate/migrations/20250523/repos-09
  migrate/migrations/20250523/repos.sh
  migrate/migrations/20250523/repos.txt
  migrate/migrations/20250523/script.sh
  migrate/templates/terraform-module/atmos.yaml
Labels: needs-cloudposse

#179 Update migration readme script to remove includes
  .github/workflows/shared-atmos-readme.yml
  .github/workflows/shared-terraform-module.yml
  migrate/lib/readme.py
  migrate/migrations/20250523/script.sh
Labels: triage, needs-cloudposse
